### ISSUE TITLE
Error? in mcmod.info

### ISSUE THREAD

**Issue by Hjaldar** [Tim020/Tiny-Storage#2]
Tiny Storage fails to load for me, with the error below in the FML client log. The fix I found was to change

"dependencies": [""]

to

"dependencies": []

in the mcmod.info file in your jar. Happy to supply more details, just not sure what you might need.

Error log below...

[14:29:30] [Client thread/DEBUG] [FML/]: Examining file TinyStorage-1.7.10-1.7.6-RC.jar for potential mods
[14:29:30] [Client thread/TRACE] [FML/]: Located mcmod.info file in file TinyStorage-1.7.10-1.7.6-RC.jar
[14:29:30] [Client thread/WARN] [FML/]: Zip file TinyStorage-1.7.10-1.7.6-RC.jar failed to read properly, it will be ignored
java.lang.RuntimeException: Empty reference 
    at cpw.mods.fml.common.versioning.VersionParser.parseVersionReference(VersionParser.java:44) ~[VersionParser.class:?]
    at cpw.mods.fml.common.MetadataCollection$ArtifactVersionAdapter.read(MetadataCollection.java:120) ~[MetadataCollection$ArtifactVersionAdapter.class:?]
    at cpw.mods.fml.common.MetadataCollection$ArtifactVersionAdapter.read(MetadataCollection.java:108) ~[MetadataCollection$ArtifactVersionAdapter.class:?]
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[TypeAdapterRuntimeTypeWrapper.class:?]
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81) ~[CollectionTypeAdapterFactory$Adapter.class:?]
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) ~[CollectionTypeAdapterFactory$Adapter.class:?]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[ReflectiveTypeAdapterFactory$1.class:?]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[ReflectiveTypeAdapterFactory$Adapter.class:?]
    at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
    at com.google.gson.Gson.fromJson(Gson.java:868) ~[Gson.class:?]
    at com.google.gson.Gson.fromJson(Gson.java:841) ~[Gson.class:?]
    at cpw.mods.fml.common.MetadataCollection.from(MetadataCollection.java:64) ~[MetadataCollection.class:?]
    at cpw.mods.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:53) [JarDiscoverer.class:?]
    at cpw.mods.fml.common.discovery.ContainerType.findMods(ContainerType.java:42) [ContainerType.class:?]
    at cpw.mods.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71) [ModCandidate.class:?]
    at cpw.mods.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:127) [ModDiscoverer.class:?]
    at cpw.mods.fml.common.Loader.identifyMods(Loader.java:347) [Loader.class:?]
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:468) [Loader.class:?]
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

**Comment by Tim020** [comment]
Hopefully fixed this now, will build and test when home from college.

**Comment by Hjaldar** [comment]
Thanks. Confirmed fixed from my end.
